name: tigol-bioquote

services:
  postgres:
    image: postgres:16
    container_name: tigol-bioquote-postgres
    restart: unless-stopped
    command: postgres -p ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      tigol-bioquote-network:
        ipv4_address: 172.22.0.2
    profiles: ['database', 'all']

  server:
    container_name: tigol-bioquote-server
    build:
      context: .
    ports:
      - "8001:8000"
    environment:
      TIGOL_CLIENT_ID: ${TIGOL_CLIENT_ID}
      TIGOL_CLIENT_SECRET: ${TIGOL_CLIENT_SECRET}
      TIGOL_REDIRECT_URI: ${TIGOL_REDIRECT_URI}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      DB_DSN: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    networks:
      tigol-bioquote-network:
        ipv4_address: 172.22.0.3
    profiles: ['server', 'all']

networks:
  tigol-bioquote-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

volumes:
  db-data:
    driver: local
